sudo: false
language: ruby
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundler --version
rvm:
  - jruby-1.7
  - jruby-9000
  - jruby-head
jdk:
  - oraclejdk7
  - oraclejdk8
matrix:
  allow_failures:
    - rvm: jruby-head
