language: ruby
before_install:
  - gem update --system
  - gem --version
  - gem install bundler
  - bundler --version
rvm:
  - jruby
  - jruby-head
jdk:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
matrix:
  exclude:
    - rvm: jruby-head
      jdk: openjdk6
  allow_failures:
    - rvm: jruby-head
